force-app/main/default/objects/CF_LogRecord__c/CF_LogRecord__c.object-meta.xml
<CustomObject>
    <description>Define structure for records of log entries that will be stored by the common logger framework</description>
    <label>CF Log Record</label>
    <nameField>
        <displayFormat>LOG-{00000000}</displayFormat>
        <label>Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CF Log Records</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CF_LogRecord__c/fields/Running_User__c.field-meta.xml
<CustomField>
    <fullName>Running_User__c</fullName>
    <label>Running User</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/CF_LogRecordController.cls
public with sharing class CF_LogRecordController {
    @AuraEnabled(Cacheable=true)
    public static CF_LogRecord__c[] getAllLogRecs() {
        return [SELECT Id, Name, Title__c, Reason__c, Running_User__c
            FROM CF_LogRecord__c ORDER BY Name Desc LIMIT 16];
    }

    @AuraEnabled(Cacheable=true)
    public static CF_LogRecord__c[] searchLogRecs(String searchTerm) {
        // Return all log records when no search term
        searchTerm = searchTerm.trim();
        if (searchTerm == '') {
            return getAllLogRecs();
        }
        // Prepare query paramters
        searchTerm = '%'+ searchTerm +'%';
        // Execute search query
        return [SELECT Id, Name, Title__c, Reason__c, Running_User__c
            FROM CF_LogRecord__c WHERE Title__c LIKE :searchTerm ORDER BY Name DESC LIMIT 16];
    }    
}